export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';

export const SELECT_PERSON = 'App/SELECT_PERSON';

export const GET_PEOPLE_PENDING = 'App/GET_PEOPLE_PENDING';
export const GET_PEOPLE_SUCCESS = 'App/GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_ERROR = 'App/GET_PEOPLE_ERROR';

export const PUT_PERSON_PENDING = 'App/PUT_PERSON_PENDING';
export const PUT_PERSON_SUCCESS = 'App/PUT_PERSON_SUCCESS';
export const PUT_PERSON_ERROR = 'App/PUT_PERSON_ERROR';

export const DEL_PERSON_PENDING = 'App/DEL_PERSON_PENDING';
export const DEL_PERSON_SUCCESS = 'App/DEL_PERSON_SUCCESS';
export const DEL_PERSON_ERROR = 'App/DEL_PERSON_ERROR';

export const ADD_PERSON_SUCCESS = 'App/ADD_PERSON_SUCCESS';
export const ADD_PERSON_PENDING = 'App/ADD_PERSON_PENDING';
export const ADD_PERSON_ERROR = 'App/ADD_PERSON_ERROR';

export const GET_MESSAGES_SUCCESS = 'App/GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_PENDING = 'App/GET_MESSAGES_PENDING';
export const GET_MESSAGES_ERROR = 'App/GET_MESSAGES_ERROR';

export const API_BASE_URL = '//break-poverty-hackathon.herokuapp.com/api';

export const MESSAGE_PERSON_SUCCESS = 'App/MESSAGE_PERSON_SUCCESS';
export const MESSAGE_PERSON_PENDING = 'App/MESSAGE_PERSON_PENDING';
export const MESSAGE_PERSON_ERROR = 'App/MESSAGE_PERSON_ERROR';

export const SET_RECURRING_MESSAGE_SUCCESS = 'App/SET_RECURRING_MESSAGE_SUCCESS';
export const SET_RECURRING_MESSAGE_PENDING = 'App/SET_RECURRING_MESSAGE_PENDING';
export const SET_RECURRING_MESSAGE_ERROR = 'App/SET_RECURRING_MESSAGE_ERROR';
